### PR TITLE
Add simple movement/backlash compensation.

### PR DESCRIPTION
**Pull request by dogtopus**
Mainly affects CNC machines due to the potential use of gear boxes, lead screws, etc. but could also be a problem for some badly designed 3D printers.

Significantly improves dimensional accuracy on some printers such as Easythreed X1 which uses geared stepper motors with presumably too much tolerance on the gears.

Does not yet handle cases where the movement is out-of-bounds. Suggesstions are welcome.

### CODE REVIEW

**Comment by norpchen** [comment]
Can we change the new command line -X -Y -Z options to something else? Case-sensitive command line arguments can be problematic.  Maybe something like -xc -yc and -zc?

**Comment by dogtopus** [comment]
Or just drop the short form since xc yc zc might be in conflict with -c

**Comment by dogtopus** [comment]
I changed them to --{x,y,z}c instead. They are reasonably short and doesn't cause any conflicts.

The full --{x,y,z}compensate form still exist.

EDIT: ~~Hold off on merging! Something is broken.~~ Fixed.

**Comment by norpchen** [comment]
Thank you

**Pull request merged**
